Supinfo\WebBundle\Entity\Article:
    type: entity
    table: articles
    repositoryClass: 'Supinfo\WebBundle\Repository\ArticleRepository'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 15
            nullable: true
        description:
            type: string
            length: 255
        state:
            type: integer
        quantity:
            type: integer
    manyToOne:
        place:
            targetEntity: Place
            joinColumn:
                name: place_id
                referencedColumnName: id
                onDelete: "SET NULL"
        subFamily:
            targetEntity: SubFamily
            joinColumn:
                name: sub_family_id
                referencedColumnName: id
                onDelete: "SET NULL"
    oneToMany:
        fieldValues:
            targetEntity: SubFamilyFieldValue
            mappedBy: article
            cascade: ["persist"]
            orphanRemoval: true
        articleLoans:
            targetEntity: ArticleLoan
            mappedBy: article