Supinfo\WebBundle\Entity\ArticleLoan:
    type: entity
    table: articles_loans
    repositoryClass: 'Supinfo\WebBundle\Repository\ArticleLoanRepository'
    id:
        loanId:
            type: integer
            column: loan_id
            generator:
                strategy: NONE
        articleId:
            type: integer
            column: article_id
            generator:
                strategy: NONE
    fields:
        quantity:
            type: integer
        dateStart:
            type: date
            column: date_start
        dateEnd:
            type: date
            column: date_end
    manyToOne:
        article:
            targetEntity: Article
            joinColumn:
                name: article_id
                referencedColumnName: id
                onDelete: "CASCADE"
        loan:
            targetEntity: Loan
            joinColumn:
                name: loan_id
                referencedColumnName: id
                onDelete: "CASCADE"