Supinfo\WebBundle\Entity\Family:
    type: entity
    table: families
    repositoryClass: 'Supinfo\WebBundle\Repository\FamilyRepository'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50
    oneToMany:
        subFamilies:
            targetEntity: SubFamily
            mappedBy: family