Supinfo\WebBundle\Entity\Place:
    type: entity
    table: places
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50