Supinfo\WebBundle\Entity\Structure:
    type: entity
    table: structures
    repositoryClass: 'Supinfo\WebBundle\Repository\StructureRepository'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            lenght: 50