Supinfo\WebBundle\Entity\SubFamily:
    type: entity
    table: sub_families
    repositoryClass: 'Supinfo\WebBundle\Repository\SubFamilyRepository'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50
    manyToOne:
        family:
            targetEntity: Family
            joinColumn:
                name: family_id
                referencedColumnName: id
                onDelete: "CASCADE"
    oneToMany:
        fields:
            targetEntity: SubFamilyField
            mappedBy: subFamily
        articles:
            targetEntity: Article
            mappedBy: subFamily