Supinfo\WebBundle\Entity\SubFamilyField:
    type: entity
    table: sub_family_fields
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50
    manyToOne:
        subFamily:
            targetEntity: SubFamily
            joinColumn:
                name: sub_family_id
                referencedColumnName: id