Supinfo\WebBundle\Entity\SubFamilyFieldValue:
    type: entity
    table: sub_family_fields_values
    repositoryClass: 'Supinfo\WebBundle\Repository\SubFamilyFieldValueRepository'
    id:
        subFamilyFieldId:
            type: integer
            column: sub_family_field_id
            generator:
                strategy: NONE
        articleId:
            type: integer
            column: article_id
            generator:
                strategy: NONE
    fields:
        value:
            type: string
            length: 255
            nullable: true
    manyToOne:
        subFamilyField:
            targetEntity: SubFamilyField
            joinColumn:
                name: sub_family_field_id
                referencedColumnName: id
                onDelete: "CASCADE"
        article:
            targetEntity: Article
            joinColumn:
                name: article_id
                referencedColumnName: id