Place_admin_new:
    pattern: /place/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:admin'
        _admin_type: "edit"

Place_admin_edit:
    pattern: /place/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:admin'
        _admin_type: "edit"

Place_admin_delete:
    pattern: /place/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:admin'
        _admin_type: "delete"

Place_admin_list:
    pattern: /place/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:admin'
        _admin_type: "list"
        page: 1
    requirements:
        page: \d+


Article_admin_new:
    pattern: /article/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:admin'
        _admin_type: "edit"

Article_admin_edit:
    pattern: /article/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:admin'
        _admin_type: "edit"

Article_admin_delete:
    pattern: /article/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:admin'
        _admin_type: "delete"

Article_admin_list:
    pattern: /article/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:admin'
        _admin_type: "list"
        page: 1
    requirements:
        page: \d+


Family_admin_new:
    pattern: /family/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:admin'
        _admin_type: "edit"

Family_admin_edit:
    pattern: /family/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:admin'
        _admin_type: "edit"

Family_admin_delete:
    pattern: /family/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:admin'
        _admin_type: "delete"

Family_admin_list:
    pattern: /family/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:admin'
        _admin_type: "list"
        page: 1
    requirements:
        page: \d+


SubFamily_admin_new:
    pattern: /sub-family/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:admin'
        _admin_type: "edit"

SubFamily_admin_edit:
    pattern: /sub-family/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:admin'
        _admin_type: "edit"

SubFamily_admin_delete:
    pattern: /sub-family/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:admin'
        _admin_type: "delete"

SubFamily_admin_list:
    pattern: /sub-family/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:admin'
        _admin_type: "list"
        page: 1
    requirements:
        page: \d+


Structure_admin_new:
    pattern: /structure/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:admin'
        _admin_type: "edit"

Structure_admin_edit:
    pattern: /structure/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:admin'
        _admin_type: "edit"

Structure_admin_delete:
    pattern: /structure/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:admin'
        _admin_type: "delete"

Structure_admin_list:
    pattern: /structure/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:admin'
        _admin_type: "list"
        page: 1
    requirements:
        page: \d+


SubFamilyField_admin_new:
    pattern: /sub-family-field/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamilyField:admin'
        _admin_type: "edit"

SubFamilyField_admin_edit:
    pattern: /sub-family-field/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamilyField:admin'
        _admin_type: "edit"

SubFamilyField_admin_delete:
    pattern: /sub-family-field/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamilyField:admin'
        _admin_type: "delete"

SubFamilyField_admin_list:
    pattern: /sub-family-field/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamilyField:admin'
        _admin_type: "list"
        page: 1
    requirements:
        page: \d+