client_Loan_new:
    pattern: /loan/new
    defaults:
        _controller: 'SupinfoWebBundle:Loan:new'

client_Loan_edit:
    pattern: /loan/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Loan:edit'
    requirements:
        id: \d+

client_Loan_view:
    pattern: /loan/view/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Loan:view'
    requirements:
        id: \d+

client_Loan_delete_article:
    pattern: /loan-article/delete/{loanId}/{articleId}
    defaults:
        _controller: 'SupinfoWebBundle:Loan:deleteArticleLoan'
    requirements:
        id: \d+
        articleLoanId: \d+

client_Loan_list:
    pattern: /loan/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Loan:list'
        page: 1
    requirements:
        page: \d+