client_Loan_new:
    pattern: /loan/new
    defaults:
        _controller: 'SupinfoWebBundle:Client\Loan:new'

client_Loan_edit:
    pattern: /loan/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Client\Loan:edit'
    requirements:
        id: \d+

client_Loan_view:
    pattern: /loan/view/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Client\Loan:view'
    requirements:
        id: \d+

client_Loan_delete_article:
    pattern: /loan-article/delete/{loanId}/{articleId}
    defaults:
        _controller: 'SupinfoWebBundle:Client\Loan:deleteArticleLoan'
    requirements:
        id: \d+
        articleLoanId: \d+

client_Loan_list:
    pattern: /loan/list/{filters}/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Client\Loan:list'
        page: 1
        filters: '1-2'
    requirements:
        page: \d+
        filters: \d+(-\d+)*

client_Article_list:
    pattern: /article/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Client\Article:list'
        page: 1
    requirements:
        page: \d+