admin_Place_new:
    pattern: /place/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:edit'

admin_Place_edit:
    pattern: /place/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:edit'

admin_Place_delete:
    pattern: /place/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:delete'

admin_Place_list:
    pattern: /place/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Place:list'
        page: 1
    requirements:
        page: \d+


admin_Article_new:
    pattern: /article/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:edit'

admin_Article_edit:
    pattern: /article/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:edit'

admin_Article_delete:
    pattern: /article/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:delete'

admin_Article_list:
    pattern: /article/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Article:list'
        page: 1
    requirements:
        page: \d+


admin_Family_new:
    pattern: /family/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:edit'

admin_Family_edit:
    pattern: /family/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:edit'

admin_Family_delete:
    pattern: /family/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:delete'

admin_Family_list:
    pattern: /family/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Family:list'
        page: 1
    requirements:
        page: \d+


admin_SubFamily_new:
    pattern: /sub-family/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:edit'

admin_SubFamily_edit:
    pattern: /sub-family/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:edit'

admin_SubFamily_edit_new_field:
    pattern: /sub-family/edit/{id}/new-field
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:editNewField'

admin_SubFamily_delete:
    pattern: /sub-family/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:delete'

admin_SubFamily_list:
    pattern: /sub-family/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\SubFamily:list'
        page: 1
    requirements:
        page: \d+


admin_Structure_new:
    pattern: /structure/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:edit'

admin_Structure_edit:
    pattern: /structure/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:edit'

admin_Structure_delete:
    pattern: /structure/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:delete'

admin_Structure_list:
    pattern: /structure/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\Structure:list'
        page: 1
    requirements:
        page: \d+


admin_User_new:
    pattern: /user/new
    defaults:
        _controller: 'SupinfoWebBundle:Admin\User:edit'

admin_User_edit:
    pattern: /user/edit/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\User:edit'

admin_User_delete:
    pattern: /user/delete/{id}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\User:delete'

admin_User_list:
    pattern: /user/list/{page}
    defaults:
        _controller: 'SupinfoWebBundle:Admin\User:list'
        page: 1
    requirements:
        page: \d+