<?php

namespace Supinfo\WebBundle\Repository;

/**
 * ArticleLoanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLoanRepository extends EntityRepository
{
}