<?php

namespace Supinfo\WebBundle\Repository;

/**
 * SubFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamilyRepository extends EntityRepository
{
}