<?php

namespace Supinfo\WebBundle\Repository;

/**
 * SubFamilyFieldValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamilyFieldValueRepository extends EntityRepository
{
}