<?php

namespace Supinfo\WebBundle\Repository;

/**
 * SubFamilyFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamilyFieldRepository extends EntityRepository
{
}