<?php

namespace Supinfo\WebBundle\Repository;

use Doctrine\Orm\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function usernameIsAvailable($username)
    {
        $qb = $this->countQB();
        
        $qb->andWhere($qb->expr()->eq(
            $qb->expr()->lower($this->getAlias().'.username'),
            $qb->expr()->lower(':username')
        ));
        
        $qb->setParameter('username',$username);

        return $qb->getQuery()->getSingleScalarResult() < 1;
    }

    public function getSearchExpr(QueryBuilder $qb)
    {
        $expr = parent::getSearchExpr($qb);

        $expr->add(
            $qb->expr()->like(
                $qb->getRootAlias().'.username',
                ':query'
            )
        );

        return $expr;
    }

}